export const  SET_CURRENT_USER='SET_CURRENT_USER';

export const SET_LOADNG='SET_LOADNG';

export const ADD_ITEM='ADD_ITEM';

export const CLEAR_FILEDS='CLEAR_FILEDS';
export const REMOVE_ITEM='REMOVE_ITEM';

export const TOGGLE_BUTTON='TOGGLE_BUTTON';
export const CLEAR_TOGGLE_BUTTON='LEAR_TOGGLE_BUTTON';
