export const  SET_CURRENT_USER='SET_CURRENT_USER';

export const GOOGLE_SIGN_IN_START='GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS='GOOGLE_SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_FAIL='GOOGLE_SIGN_IN_FAIL';

export const EMAIL_SIGN_IN_START='EMAIL_SIGN_IN_START';
export const EMAIL_SIGN_IN_SUCCESS='EMAIL_SIGN_IN_SUCCESS';
export const EMAIL_SIGN_IN_FAIL='EMAIL_SIGN_IN_FAIL';


export const SET_LOADNG='SET_LOADNG';

export const ADD_ITEM='ADD_ITEM';

export const CLEAR_FILEDS='CLEAR_FILEDS';
export const REMOVE_ITEM='REMOVE_ITEM';

export const TOGGLE_BUTTON='TOGGLE_BUTTON';
export const CLEAR_TOGGLE_BUTTON='LEAR_TOGGLE_BUTTON';

export const UPDATE_COLLECTIONS_START='UPDATE_COLLECTIONS_START';
export const UPDATE_COLLECTIONS_SUCCESS='UPDATE_COLLECTIONS_SUCCESS';
export const UPDATE_COLLECTIONS_FAIL='UPDATE_COLLECTIONS_FAIL';